source 'https://github.com/qinzhongzeng55/QZZSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QZZToolsKit_Example' do
  pod 'QZZToolsKit', :path => '../'
  pod 'FMDB'
  pod 'SDWebImage'
  pod 'QZZCategoryKit'
  pod 'FLAnimatedImage'
  target 'QZZToolsKit_Tests' do
    inherit! :search_paths

    
  end
end
